### ISSUE TITLE
hum2xml: gracenote and open phrase mark

### ISSUE THREAD

**Issue by pvankranenburg** [craigsapp/humextra#9] opened 2018-07-27 11:02 UTC
The combination of a phrase open mark and a grace note causes `hum2xml` to misinterpret the duration of the grace note.

Minimal example
```
**kern
*clefG2
*M4/4
*k[]
*C:
=7
{8gq
1a}
==
*-
```
Results in:
```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE score-partwise PUBLIC "-//Recordare//DTD MusicXML 2.0 Partwise//EN" "http://www.musicxml.org/dtds/partwise.dtd">
<score-partwise version="2.0">
	<part-list>
		<score-part id="P1">
			<part-name></part-name>
		</score-part>
	</part-list>

	<part id="P1">
		<measure number="1">
			<attributes>
				<divisions>1</divisions>
			</attributes>
			<attributes>
				<clef>
					<sign>G</sign>
					<line>2</line>
				</clef>
			</attributes>
			<attributes>
				<time>
					<beats>4</beats>
					<beat-type>4</beat-type>
				</time>
			</attributes>
			<attributes>
				<key>
					<fifths>0</fifths>
					<mode>major</mode>
				</key>
			</attributes>
			<note>
				<grace slash="yes"/>
				<pitch>
					<step>G</step>
					<octave>4</octave>
				</pitch>
				<voice>1</voice>
				<type>breve</type>
			</note>
			<note>
				<pitch>
					<step>A</step>
					<octave>4</octave>
				</pitch>
				<duration>4</duration>
				<voice>1</voice>
				<type>whole</type>
			</note>
		</measure>
	</part>
</score-partwise>
```
Here, the `type` of the grace note is `breve`, but should be `eighth`. Either removing the open phrase mark `{` or the grace note indication `q` solves this problem.

**Comment by craigsapp** [comment] 2018-07-27 21:37
Should now be fixed with commit https://github.com/craigsapp/humextra/commit/5434470fa1fecf5b01453920269355fc821d4d53

The problem is that for grace notes, any non-digits before the rhythm were not being removed, and then the extracted number was 0 instead of 8, and 0 means breve in `**kern` data.

Here is what the new output for the test data should produce:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE score-partwise PUBLIC "-//Recordare//DTD MusicXML 2.0 Partwise//EN" "http://www.musicxml.org/dtds/partwise.dtd">
<score-partwise version="2.0">
	<part-list>
		<score-part id="P1">
			<part-name></part-name>
		</score-part>
	</part-list>

	<part id="P1">
		<measure number="1">
			<attributes>
				<divisions>1</divisions>
			</attributes>
			<attributes>
				<clef>
					<sign>G</sign>
					<line>2</line>
				</clef>
			</attributes>
			<attributes>
				<time>
					<beats>4</beats>
					<beat-type>4</beat-type>
				</time>
			</attributes>
			<attributes>
				<key>
					<fifths>0</fifths>
					<mode>major</mode>
				</key>
			</attributes>
			<note>
				<grace slash="yes"/>
				<pitch>
					<step>G</step>
					<octave>4</octave>
				</pitch>
				<voice>1</voice>
				<type>eighth</type>
			</note>
			<note>
				<pitch>
					<step>A</step>
					<octave>4</octave>
				</pitch>
				<duration>4</duration>
				<voice>1</voice>
				<type>whole</type>
			</note>
		</measure>
	</part>
</score-partwise>
```

Here is the graphical rendering of the above data with MuseScore 2.2:

<img width="629" alt="screen shot 2018-07-27 at 11 27 22 pm" src="https://user-images.githubusercontent.com/3487289/43347213-c62817ca-91f4-11e8-82cf-e623a5a7bc0d.png">

**Closed by craigsapp** 2018-07-27 21:37 UTC
